services:
  backend:
    build: ./Backend
    container_name: "Backend"
    restart: unless-stopped
    ports:
      - "127.0.0.1:3000:3000"
    env_file:
      - ./Backend/.env
    depends_on:
      - prom-server

  frontend:
    build: ./Frontend
    container_name: "Frontend"
    restart: unless-stopped
    ports:
      - "127.0.0.1:4173:4173"
    env_file:
      - ./Frontend/.env

  prom-server:
    image: prom/prometheus
    container_name: "Prometheus"
    restart: unless-stopped
    ports:
      - "127.0.0.1:9090:9090"
    volumes:
      - ./Backend/prometheus-config.yml:/etc/prometheus/prometheus.yml
