global:
  scrape_interval: 4s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: backend
    static_configs:
      - targets: ['backend:3000']

  - job_name: cadvisor
    static_configs:
      - targets: ['cadvisor:8080']
